<?PHP
//$Id$

	/**
	 *Implementation of hook_perm().
	 **/
	function yelp_perm(){
		return array('administer yelp','add yelp block','edit yelp block','delete yelp block');
	}

	/**
	 * Implements hook_access()
	 */
	function yelp_access($op){
		return user_access($op);
	}

	/**
	 * Implementation of hook_menu().
	 */
	function yelp_menu() {
		$items['admin/content/yelp'] = array(
			'title' => 'Yelp',
			'description' => "Manage your sites Page specific Yelp Blocks.",
			'page callback' => 'yelp_admin_overview',
			'access arguments' => array('administer yelp'),
			'file' => 'yelp.admin.inc',
		);
  
		$items['admin/content/yelp/list'] = array(
			'title' => 'List',
			'type' => MENU_DEFAULT_LOCAL_TASK,
		);
  
		$items['admin/content/yelp/settings'] = array(
			'title' => 'Settings',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('yelp_admin_settings'),
			'access arguments' => array('administer yelp'),
			'type' => MENU_LOCAL_TASK,
			'weight' => 8,
			'file' => 'yelp.admin.inc',
		);
  
		$items['admin/content/yelp/add'] = array(
			'title' => 'Add Yelp Block',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('yelp_form_block'),
			'access arguments' => array('add yelp block'),
			'type' => MENU_LOCAL_TASK,
			'weight' => 10,
			'file' => 'yelp.admin.inc',
		);
  
		$items['admin/content/yelp/edit/%yelp_block'] = array(
			'title' => 'Edit Yelp Block',
			'page callback' => 'yelp_form_edit_block',
			'page arguments' => array(4),
			'access arguments' => array('edit yelp block'),
			'type' => MENU_CALLBACK,
			'file' => 'yelp.admin.inc',
		);
		
		$items['admin/content/yelp/delete/%yelp_block'] = array(
			'title' => 'Delete Yelp Block',
			'page callback' => 'yelp_pre_delete_block',
			'page arguments' => array(4),
			'access arguments' => array('delete yelp block'),
			'type' => MENU_CALLBACK,
			'file' => 'yelp.admin.inc',
		);
		return $items;
	}

	/**
	 * Implementation of hook_theme();
	 */
	function yelp_theme() {
		return array(
			'yelp_block'=>array(
				'arguments' => array('block' => array(),'delta'=> NULL),
				'template' => 'yelp-block',
			),
			'yelp_business'=>array(
				'arguments' => array('business' => array(), 'delta' => NULL),
				'template' => 'yelp-business',
			),
		);
	}

	/**
	 * Implementation of hook_block();
	 */
	function yelp_block($op = 'list', $delta = 0, $edit = array()) {
		switch ($op) {
			case 'list':
				$block = array();
				$block[0]["info"] = t('Yelp Search Results');
				break;
			case 'view': default:
				//If this node has a custom yelp block
				if($nid = yelp_node_block()){
					//retrieve the block content
					$block['content'] = yelp_display_businesses($nid);
				}
		}
		return $block;
	}

	/**
	 * Retrieves HTML content for displaying Businesses returned from Yelp search
	 **/
	function yelp_display_businesses($nid){
		//get block settings
		$sql = "SELECT * FROM {yelp_blocks} WHERE `nid` = %d";
		//If we find the Yelp block
		if($settings = db_fetch_object(db_query($sql,$nid))){
			//Attempt to Retrieve businesses from Yelp.
			if($businesses = yelp_get_businesses(yelp_format_query($settings))){
				//Successful, need to theme each returned business.
				foreach($businesses as $x=>$r){	
					$temp .= theme('yelp_business',$r,$x);
				}
				//Yelp.com requires their logo to be displayed.
				$temp.='<p>Results from <a target="_blank" href="http://www.yelp.com/"><img src="http://static.px.yelp.com/static/20090804/i/map/miniMapLogo.png" alt="Businesses from Yelp" style="display:inline;visibility:visible;border:0px;vertical-align:bottom;" /></a></p>';
			}else{
				//Failed to retireve businesses
				$businesses = array();
				$temp = '';
			}
			$settings->found = sizeof($businesses);
			$settings->businesses = strlen($temp)>1 ? $temp:false;
			
			//Themes the Yelp block and return
			return theme('yelp_block',$settings,$settings->yid);
		}
		//Return blank.
		return '';
	}

	/**
	 * Retrieve businesses from Yelp.com API.
	 **/
	function yelp_get_businesses($query){
		$result = file_get_contents("http://api.yelp.com/business_review_search?".$query);
		$result = json_decode($result);
		//If Yelp has returned businesses, then return them
		if($result->message->text == 'OK'){
			return $result->businesses;
		}else{
			//No businesses returned, so return false.
			return false;
		}
	}

	/**
	 * Builds API query to send to Yelp.com for this Yelp block
	 **/
	function yelp_format_query($block_settings){
		//need API key, if there is'nt one return false.
		if(!$api_key = variable_get('yelp_api_key',0)) return false;
	
		//build query required fields.
		$query = array(
			'location='.urlencode(trim($block_settings->location)),
			'radius='.trim($block_settings->radius),
			'num_biz_requested='.trim($block_settings->max)
		);
	
		//If given categories for this block, then add the string to the category.
		if(strlen($block_settings->categories)>1){
			$query[] = 'category='.trim($block_settings->categories);
		}
		
		//Add the API key last to the query.
		$query[] = 'ywsid='.$api_key;
	
		//return the query string.
		return implode('&',$query);
	}

	/**
	 * Checks current node to see if it has a custom Yelp Block
	 **/
	function yelp_node_block(){
		//First need the node NID. if not found return false
		if(!$nid = yelp_get_current_nid()) return false;
		
		//Check to see if current node has a custom yelp block
		$sql = "SELECT yid FROM {yelp_blocks} WHERE `nid` = %d";
		$result = db_fetch_object(db_query($sql,$nid));
		
		//if not assigned a yelp block, return false.
		if(!$result->yid) return false;
		
		//else return the node Id
		return $nid;
	}
	
	/**
	 * Retireve the NID of the current node
	 **/
	function yelp_geT_current_nid(){
		if (arg(0) == 'node' && is_numeric(arg(1)) && is_null(arg(2))) return (int)arg(1);
		else if($_GET['q']) return (int)substr($_GET['q'],strrpos($_GET['q'],"/")+1);
		return false;
	}


	/**
	 * Retrieve values of a Yelp Block
	 **/
	function yelp_block_load($yid){
		$sql = "SELECT * FROM {yelp_blocks} WHERE `yid` = %d";
		return db_fetch_object(db_query($sql,$yid));
	}

	/**
	 * Save settings for a yelp block
	 **/
	function yelp_save_block($values){
		$temp = array();
		$temp['title']  	= check_plain($values['title']);
		$temp['nid']		= $values['nid'];
		$temp['location'] 	= check_plain($values['location']);
		$temp['radius']		= $values['radius'];
		$temp['max']		= $values['max'];
		//Need to check with categories have been checked (recursive)
		$temp['categories'] = yelp_save_categories($values,array(),yelp_get_categories());
		//If array of categories implode with  '+', else set to blank.
		$temp['categories'] = sizeof($temp['categories'])>0 ? implode('+',$temp['categories']):'';
		
		//If there already is not a yid, then we're creating a block
		if(!$values['yid']){
			$sql = "INSERT INTO {yelp_blocks}(`title`,`nid`,`location`,`radius`,`max`,`categories`) VALUES ('%s',%d,'%s',%d,%d,'%s')";
		//Else updating an existing block
		}else{
			$sql = "UPDATE {yelp_blocks} SET `title` = '%s', `nid` = %d, `location` = '%s', `radius` = %d, `max` = %d, `categories` = '%s' WHERE `yid` = %d";
			$temp['yid'] = $values['yid'];
		}
		//run query
		db_query($sql,$temp);
		
		if($temp['yid']) return SAVED_UPDATED;
		else return SAVED_NEW;
	}

	/**
	 * Delete a Yelp Block
	 **/
	function yelp_delete_block($yid){
		$sql = "DELETE FROM {yelp_blocks} WHERE `yid` = %d";
		db_query($sql,$yid);
	}

	/**
	 * Recursive function to see which categories have been checked for a block
	 * returns an array of category names
	 **/
	function yelp_save_categories($values,$saved,$categories){
		//foreach category
		foreach($categories as $c){
			//if $c is an array (has sub categories)
			if(is_array($c)){
				//check sub categories
				$saved = yelp_save_categories($values, $saved, $c[1]);
				//set $c to $c[0]; wich is the category title
				$c = $c[0];
			}
			
			//see if category is selected, and not already saved add it to saved array
			if($values[$c] == 1 && !in_array($c,$saved)){
				$saved[] = $c;
			}
		}
		
		//return array of checked categories
		return $saved;
	}
	
	/**
	 * Return multi level array of Yelp.com search categories
	 **/
	function yelp_get_categories(){
		return array('Active Life'=>array('active',array(
			'Amateur Sports Teams'=>'amateursportsteams',
		'Amusement Parks'=>'amusementparks',
		'Aquariums'=>'aquariums',
		'Beaches'=>'beaches',
		'Bike Rentals'=>'bikerentals',
		'Boating'=>'boating',
		'Bowling'=>'bowling',
		'Diving'=>'diving',
		'Fitness & Instruction'=>array('fitness',array(
			'Dance Studios'=>'dancestudio',
			'Gyms'=>'gyms',
			'Martial Arts'=>'martialarts',
			'Pilates'=>'pilates',
			'Trainers'=>'healthtrainers',
			'Yoga'=>'yoga')),
		'Golf'=>'golf',
		'Gun/Rifle Ranges'=>'gun_ranges',
		'Hiking'=>'hiking',
		'Lakes'=>'lakes',
		'Leisure Centers'=>'leisure_centers',
		'Mini Golf'=>'mini_golf',
		'Parks'=>array('parks',array(
			'Dog Parks'=>'dog_parks',
			'Skate Parks'=>'skate_parks')),
		'Playgrounds'=>'playgrounds',
		'Rafting/Kayaking'=>'rafting',
		'Skating Rinks'=>'skatingrinks',
		'Soccer'=>'football',
		'Sports Clubs'=>'sports_clubs',
		'Summer Camps'=>'summer_camps',
		'Swimming Pools'=>'swimmingpools',
		'Tennis'=>'tennis',
		'Zoos'=>'zoos')),
    'Arts & Entertainment'=>array('arts',array(
		'Arcades'=>'arcades',
		'Art Galleries'=>'galleries',
		'Botanical Gardens'=>'gardens',
		'Casinos'=>'casinos',
		'Cinema'=>'movietheaters',
		'Jazz & Blues'=>'jazzandblues',
		'Museums'=>'museums',
		'Music Venues'=>'musicvenues',
		'Performing Arts'=>'theater',
		'Professional Sports Teams'=>'sportsteams',
		'Psychics & Astrologers'=>'psychic_astrology',
		'Social Clubs'=>'social_clubs',
		'Stadiums & Arenas'=>'stadiumsarenas',
		'Wineries'=>'wineries')),
    'Automotive'=>array('auto',array(
		'Auto Detailing'=>'auto_detailing',
		'Auto Glass Services'=>'autoglass',
		'Auto Repair'=>'autorepair',
		'Body Shops'=>'bodyshops',
		'Car Dealers'=>'car_dealers',
		'Car Wash'=>'carwash',
		'Gas & Service Stations'=>'servicestations',
		'Motorcycle Dealers'=>'motorcycledealers',
		'Motorcycle Repair'=>'motorcyclerepair',
		'Parking'=>'parking',
		'Smog Check Stations'=>'smog_check_stations',
		'Stereo Installation'=>'stereo_installation',
		'Tires'=>'tires',
		'Towing'=>'towing')),
    'Beauty and Spas'=>array('beautysvc',array(
		'Barbers'=>'barbers',
		'Cosmetics & Beauty Supply'=>'cosmetics',
		'Day Spas'=>'spas',
		'Hair Removal'=>array('hairremoval',array(
			'Laser Hair Removal'=>'laser_hair_removal')),
		'Hair Salons'=>'hair',
		'Makeup Artists'=>'makeupartists',
		'Massage'=>'massage',
		'Nail Salons'=>'othersalons',
		'Piercing'=>'piercing',
		'Skin Care'=>'skincare',
		'Tanning'=>'tanning',
		'Tattoo'=>'tattoo')),
    'Education'=>array('education',array(
		'Adult Education'=>'adultedu',
		'Colleges & Universities'=>'collegeuniv',
		'Elementary Schools'=>'elementaryschools',
		'Middle Schools & High Schools'=>'highschools',
		'Preschools'=>'preschools',
		'Specialty Schools'=>array('specialtyschools',array(
			'Art Schools'=>'artschools',
			'Cooking Schools'=>'cookingschools',
			'Cosmetology Schools'=>'cosmetology_schools',
			'Dance Schools'=>'dance_schools',
			'Driving Schools'=>'driving_schools',
			'Language Schools'=>'language_schools',
			'Massage Schools'=>'massage_schools')),
		'Tutoring Centers'=>'tutoring')),
    'Event Planning & Services'=>array('eventservices',array(
		'Boat Charters'=>'boatcharters',
		'Cards & Stationery'=>'stationery',
		'Caterers'=>'catering',
		'DJs'=>'djs',
		'Hotels'=>'hotels',
		'Party & Event Planning'=>'eventplanning',
		'Party Supplies'=>'partysupplies',
		'Personal Chefs'=>'personalchefs',
		'Photographers'=>'photographers',
		'Venues & Event Spaces'=>'venues',
		'Wedding Planning'=>'wedding_planning')),
    'Financial Services'=>array('financialservices',array(
		'Banks & Credit Unions'=>'banks',
		'Insurance'=>'insurance',
		'Investing'=>'investing')),
    'Food'=>array('food',array(
		'Bagels'=>'bagels',
		'Bakeries'=>'bakeries',
		'Beer, Wine & Spirits'=>'beer_and_wine',
		'Breweries'=>'breweries',
		'Coffee & Tea'=>'coffee',
		'Convenience Stores'=>'convenience',
		'Desserts'=>'desserts',
		'Donuts'=>'donuts',
		'Farmers Market'=>'farmersmarket',
		'Grocery'=>'grocery',
		'Ice Cream & Frozen Yogurt'=>'icecream',
		'Juice Bars & Smoothies'=>'juicebars',
		'Specialty Food'=>array('gourmet',array(
			'Candy Stores'=>'candy',
			'Cheese Shops'=>'cheese',
			'Chocolatiers and Shops'=>'chocolate',
			'Ethnic Food'=>'ethnicmarkets',
			'Fruits & Veggies'=>'markets',
			'Health Markets'=>'healthmarkets',
			'Meat Shops'=>'meats',
			'Seafood Markets'=>'seafoodmarkets')),
		'Tea Rooms'=>'tea',
		'Wineries'=>'wineries')),
    'Health and Medical'=>array('health',array(
		'Acupuncture'=>'acupuncture',
		'Cannabis Clinics'=>'cannabis_clinics',
		'Chiropractors'=>'chiropractors',
		'Counseling & Mental Health'=>'c_and_mh',
		'Dentists'=>array('dentists',array(
			'Oral Surgeons'=>'oralsurgeons',
			'Orthodontists'=>'orthodontists',
			'Pediatric Dentists'=>'pediatric_dentists')),
		'Doctors'=>array('physicians',array(
			'Cardiologists'=>'cardiology',
			'Cosmetic Surgeons'=>'cosmeticsurgeons',
			'Dermatologists'=>'dermatology',
			'Ear Nose & Throat'=>'earnosethroat',
			'Family Practice'=>'familydr',
			'Internal Medicine'=>'internalmed',
			'Naturopathic/Holistic'=>'naturopathic',
			'Obstetricians and Gynecologists'=>'obgyn',
			'Ophthalmologists'=>'opthamalogists',
			'Orthopedists'=>'orthopedists',
			'Pediatricians'=>'pediatricians',
			'Podiatrists'=>'podiatrists',
			'Psychiatrists'=>'psychiatrists',
			'Sports Medicine'=>'sportsmed')),
		'Hospitals'=>'hospitals',
		'Medical Centers'=>'medcenters',
		'Midwives'=>'midwives',
		'Nutritionists'=>'nutritionists',
		'Optometrists'=>'optometrists',
		'Physical Therapy'=>'physicaltherapy',
		'Retirement Homes'=>'retirement_homes',
		'Urgent Care'=>'urgent_care')),
    'Home Services'=>array('homeservices',array(
		'Building Supplies'=>'buildingsupplies',
		'Carpeting'=>'carpeting',
		'Contractors'=>'contractors',
		'Electricians'=>'electricians',
		'Flooring'=>'flooring',
		'Gardeners'=>'gardeners',
		'Home Cleaning'=>'homecleaning',
		'Home Inspectors'=>'home_inspectors',
		'Interior Design'=>'interiordesign',
		'Keys & Locksmiths'=>'locksmiths',
		'Landscaping'=>'landscaping',
		'Lighting Fixtures & Equipment'=>'lighting',
		'Movers'=>'movers',
		'Painters'=>'painters',
		'Plumbing'=>'plumbing',
		'Real Estate'=>array('realestate',array(
			'Apartments'=>'apartments',
			'Mortgage Brokers'=>'mortgagebrokers',
			'Property Management'=>'propertymgmt',
			'Real Estate Agents'=>'realestateagents',
			'Real Estate Services'=>'realestatesvcs',
			'University Housing'=>'university_housing')),
		'Shades & Blinds'=>'blinds')),
    'Hotels & Travel'=>array('hotelstravel',array(
		'Airports'=>'airports',
		'Bed & Breakfast'=>'bedbreakfast',
		'Campgrounds'=>'campgrounds',
		'Car Rental'=>'carrental',
		'Guest Houses'=>'guesthouses',
		'Hostels'=>'hostels',
		'Hotels'=>'hotels',
		'Ski Resorts'=>'skiresorts',
		'Tours'=>'tours',
		'Transportation'=>array('transport',array(
			'Airlines'=>'airlines',
			'Airport Shuttles'=>'airport_shuttles',
			'Limos'=>'limos',
			'Public Transportation'=>'publictransport',
			'Taxis'=>'taxis')),
		'Travel Services'=>'travelservices')),
    'Local Flavor'=>'localflavor',
    'Local Services'=>array('localservices',array(
		'Appliances & Repair'=>'homeappliancerepair',
		'Carpet Cleaning'=>'carpet_cleaning',
		'Child Care & Day Care'=>'childcare',
		'Community Service/Non-Profit'=>'nonprofit',
		'Couriers & Delivery Services'=>'couriers',
		'Dry Cleaning & Laundry'=>'drycleaninglaundry',
		'Funeral Services & Cemeteries'=>'funeralservices',
		'Furniture Reupholstery'=>'reupholstery',
		'IT Services & Computer Repair'=>'itservices',
		'Notaries'=>'notaries',
		'Pest Control'=>'pest_control',
		'Printing Services'=>'copyshops',
		'Recording & Rehearsal Studios'=>'recording_studios',
		'Self Storage'=>'selfstorage',
		'Sewing & Alterations'=>'sewingalterations',
		'Shipping Centers'=>'shipping_centers',
		'Shoe Repair'=>'shoerepair',
		'Watch Repair'=>'watch_repair')),
		'Mass Media'=>array('massmedia',array(
			'Print Media'=>'printmedia',
			'Radio Stations'=>'radiostations',
			'Television Stations'=>'televisionstations')),
		'Nightlife'=>array('nightlife',array(
			'Adult Entertainment'=>'adultentertainment',
			'Bars'=>array('bars',array(
				'Champagne Bars'=>'champagne_bars',
				'Dive Bars'=>'divebars',
				'Gay Bars'=>'gaybars',
				'Hookah Bars'=>'hookah_bars',
				'Lounges'=>'lounges',
				'Pubs'=>'pubs',
				'Sports Bars'=>'sportsbars',
				'Wine Bars'=>'wine_bars')),
			'Comedy Clubs'=>'comedyclubs',
			'Dance Clubs'=>'danceclubs',
			'Jazz & Blues'=>'jazzandblues',
			'Karaoke'=>'karaoke',
			'Music Venues'=>'musicvenues',
			'Pool Halls'=>'poolhalls')),
		'Pets'=>array('pets',array(
			'Animal Shelters'=>'animalshelters',
			'Pet Services'=>array('petservices',array(
				'Dog Walkers'=>'dogwalkers',
				'Pet Boarding/Pet Sitting'=>'pet_sitting',
				'Pet Groomers'=>'groomer',
				'Pet Training'=>'pet_training')),
			'Pet Stores'=>'petstore',
			'Veterinarians'=>'vet')),
    'Professional Services'=>array('professional',array(
		'Accountants'=>'accountants',
		'Architects'=>'architects',
		'Employment Agencies'=>'employmentagencies',
		'Graphic Design'=>'graphicdesign',
		'Internet Service Providers'=>'isps',
		'Lawyers'=>array('lawyers',array(
			'Bankruptcy'=>'bankruptcy',
			'Divorce and Family Law'=>'divorce',
			'General Litigation'=>'general_litigation',
			'Personal Injury'=>'personal_injury')),
		'Web Design'=>'web_design')),
    'Public Services & Government'=>array('publicservicesgovt',array(
		'Landmarks & Historical Buildings'=>'landmarks',
		'Libraries'=>'libraries',
		'Post Offices'=>'postoffices')),
    'Real Estate'=>array('realestate',array(
		'Apartments'=>'apartments',
		'Mortgage Brokers'=>'mortgagebrokers',
		'Property Management'=>'propertymgmt',
		'Real Estate Agents'=>'realestateagents',
		'Real Estate Services'=>'realestatesvcs',
		'University Housing'=>'university_housing')),
    'Religious Organizations'=>array('religiousorgs',array(
		'Buddhist Temples'=>'buddhist_temples',
		'Churches'=>'churches',
		'Hindu Temples'=>'hindu_temples',
		'Mosques'=>'mosques',
		'Synagogues'=>'synagogues')),
    'Restaurants'=>array('restaurants',array(
		'Afghan'=>'afghani',
		'African'=>'african',
		'American (New)'=>'newamerican',
		'American (Traditional)'=>'tradamerican',
		'Argentine'=>'argentine',
		'Asian Fusion'=>'asianfusion',
		'Barbeque'=>'bbq',
		'Basque'=>'basque',
		'Belgian'=>'belgian',
		'Brasseries'=>'brasseries',
		'Brazilian'=>'brazilian',
		'Breakfast & Brunch'=>'breakfast_brunch',
		'British'=>'british',
		'Buffets'=>'buffets',
		'Burgers'=>'burgers',
		'Burmese'=>'burmese',
		'Cajun/Creole'=>'cajun',
		'Cambodian'=>'cambodian',
		'Caribbean'=>'caribbean',
		'Chicken Wings'=>'chicken_wings',
		'Chinese'=>array('chinese',array(
			'Dim Sum'=>'dimsum')),
		'Creperies'=>'creperies',
		'Cuban'=>'cuban',
		'Delis'=>'delis',
		'Diners'=>'diners',
		'Ethiopian'=>'ethiopian',
		'Fast Food'=>'hotdogs',
		'Filipino'=>'filipino',
		'Fish & Chips'=>'fishnchips',
		'Fondue'=>'fondue',
		'Food Stands'=>'foodstands',
		'French'=>'french',
		'Gastropubs'=>'gastropubs',
		'German'=>'german',
		'Gluten-Free'=>'gluten_free',
		'Greek'=>'greek',
		'Halal'=>'halal',
		'Hawaiian'=>'hawaiian',
		'Himalayan/Nepalese'=>'himalayan',
		'Hot Dogs'=>'hotdog',
		'Hungarian'=>'hungarian',
		'Indian'=>'indpak',
		'Indonesian'=>'indonesian',
		'Irish'=>'irish',
		'Italian'=>'italian',
		'Japanese'=>'japanese',
		'Korean'=>'korean',
		'Kosher'=>'kosher',
		'Latin American'=>'latin',
		'Live/Raw Food'=>'raw_food',
		'Malaysian'=>'malaysian',
		'Mediterranean'=>'mediterranean',
		'Mexican'=>'mexican',
		'Middle Eastern'=>'mideastern',
		'Modern European'=>'modern_european',
		'Mongolian'=>'mongolian',
		'Moroccan'=>'moroccan',
		'Pakistani'=>'pakistani',
		'Persian/Iranian'=>'persian',
		'Pizza'=>'pizza',
		'Polish'=>'polish',
		'Portuguese'=>'portuguese',
		'Russian'=>'russian',
		'Sandwiches'=>'sandwiches',
		'Scandinavian'=>'scandinavian',
		'Seafood'=>'seafood',
		'Singaporean'=>'singaporean',
		'Soul Food'=>'soulfood',
		'Southern'=>'southern',
		'Spanish'=>'spanish',
		'Steakhouses'=>'steak',
		'Sushi Bars'=>'sushi',
		'Taiwanese'=>'taiwanese',
		'Tapas Bars'=>'tapas',
		'Tex-Mex'=>'tex-mex',
		'Thai'=>'thai',
		'Turkish'=>'turkish',
		'Ukrainian'=>'ukrainian',
		'Vegan'=>'vegan',
		'Vegetarian'=>'vegetarian',
		'Vietnamese'=>'vietnamese')),
    'Shopping'=>array('shopping',array(
		'Adult'=>'adult',
		'Antiques'=>'antiques',
		'Art Galleries'=>'galleries',
		'Arts & Crafts'=>array('artsandcrafts',array(
			'Art Supplies'=>'artsupplies',
			'Cards & Stationery'=>'stationery',
			'Costumes'=>'costumes',
			'Fabric Stores'=>'fabricstores',
			'Framing'=>'framing')),
    'Baby Gear & Furniture'=>'baby_gear',
    'Books, Mags, Music and Video'=>array('media',array(
		'Bookstores'=>'bookstores',
		'Comic Books'=>'comicbooks',
		'Music & DVD\'s'=>'musicvideo',
		'Newspapers & Magazines'=>'mags',
		'Videos and Video Game Rental'=>'videoandgames',
		'Vinyl Records'=>'vinyl_records')),
    'Bridal'=>'bridal',
    'Computers'=>'computers',
    'Cosmetics & Beauty Supply'=>'cosmetics',
    'Department Stores'=>'deptstores',
    'Drugstores'=>'drugstores',
    'Electronics'=>'electronics',
    'Eyewear & Opticians'=>'opticians',
    'Fashion'=>array('fashion',array(
		'Accessories'=>'accessories',
		'Children\'s Clothing'=>'childcloth',
		'Department Stores'=>'deptstores',
		'Leather Goods'=>'leather',
		'Lingerie'=>'lingerie',
		'Maternity Wear'=>'maternity',
		'Men\'s Clothing'=>'menscloth',
		'Shoe Stores'=>'shoes',
		'Sports Wear'=>'sportswear',
		'Used, Vintage & Consignment'=>'vintage',
		'Women\'s Clothing'=>'womenscloth')),
    'Flowers & Gifts'=>array('flowers',array(
		'Cards & Stationery'=>'stationery',
		'Florists'=>'florists')),
    'Hobby Shops'=>'hobbyshops',
    'Home & Garden'=>array('homeandgarden',array(
		'Appliances'=>'appliances',
		'Furniture Stores'=>'furniture',
		'Hardware Stores'=>'hardware',
		'Home Decor'=>'homedecor',
		'Kitchen & Bath'=>'kitchenandbath',
		'Mattresses'=>'mattresses',
		'Nurseries & Gardening'=>'gardening')),
    'Jewelry'=>'jewelry',
    'Luggage'=>'luggage',
    'Mobile Phones'=>'mobilephones',
    'Musical Instruments & Teachers'=>'musicalinstrumentsandteachers',
    'Office Equipment'=>'officeequipment',
    'Outlet Stores'=>'outlet_stores',
    'Pawn Shops'=>'pawn',
    'Personal Shopping'=>'personal_shopping',
    'Photography Stores & Services'=>'photographystores',
    'Shopping Centers'=>'shoppingcenters',
    'Sporting Goods'=>array('sportgoods',array(
			'Bikes'=>'bikes',
			'Outdoor Gear'=>'outdoorgear',
			'Sports Wear'=>'sportswear')),
    'Thrift Stores'=>'thrift_stores',
    'Tobacco Shops'=>'tobaccoshops',
    'Toy Stores'=>'toys',
    'Watches'=>'watches',
	'Wholesale Stores'=>'wholesale_stores')));
}