<?php

function yelp_business_menu() {
  $items = array();

  $items['yelp-business-lookup/%'] = array(
    'title'             => 'Yelp Business Lookup',
    'page callback'     => 'yelp_business_lookup',
    'page arguments'    => array(1),
    'access arguments'  => array('access content'),
    'file path'         => drupal_get_path('module', 'yelp_business') .'/includes',
    'file'              => 'yelp_business.api.inc',
    'delivery callback' => 'drupal_json_output',
  );

  return $items;
}
